name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@64.181.182.85 'cd ~/dazanimes/backend/ && git pull origin main && npm install && cd ~/dazanimes/frontend/ && git pull origin main && npm install && cd ~/dazanimes/ && pm2 restart all'
